[package]
name = "cpc"
version = "0.1.0"
description = "evaluates math expressions, with support for units and conversion between units"
readme = 'README.md'
authors = ["Kasper Henningsen"]
edition = "2018"
repository = "https://github.com/probablykasper/cpc"

[dependencies]
decimal = "2.0.4"
