[package]
name = "cpc"
version = "0.1.0"
description = "evaluates math expressions, with support for units and conversion between units"
authors = ["Kasper Henningsen"]
edition = "2018"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/probablykasper/cpc#readme"
repository = "https://github.com/probablykasper/cpc"
keywords = ["cpc", "math", "expression", "string", "evaluator", "eval", "units", "convert", "conversion"]
categories = ["mathematics", "science", "parsing", "text-processing", "value-formatting"]

[dependencies]
decimal = "2.0.4"
